#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.7.8 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=72,1,2,3,4,5,9,19,41,43,52,53,54,55,60,62&i=1,2,3,4,15,16,17,27,28,29,30,31,32,33,34&v=21,22,-1,32,25,27,26,14,36,34,39,35,33,13,4 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ILI9341, OneButton, XPT2046_Touchscreen */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE			RU

#define DSP_MODEL			DSP_ILI9341
#define TFT_DC			21
#define TFT_CS			    22
#define BRIGHTNESS_PIN			32

#define I2S_DOUT			25
#define I2S_BCLK			27
#define I2S_LRC			    26

#define BTN_MODE			14

#define ENC_BTNR			35
#define ENC_BTNL			33
#define ENC_BTNB			13
#define ENC_INTERNALPULLUP	true
#define ENC_HALFQUARD       false /*  (true, false, 255) Experiment  with it */

#define ENC2_BTNR           36
#define ENC2_BTNL           34
#define ENC2_BTNB           39
#define ENC2_INTERNALPULLUP true
#define ENC2_HALFQUARD      false          /*  Experiment  with it */

#define TS_MODEL			TS_MODEL_XPT2046
#define TS_CS			    4


#endif
